# -*- coding: utf-8 -*-
"""ml-leakage-pipeline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ri-eMjdUOq906KkU244HajRQid5NXW77
"""

import numpy as np
import pandas as pd
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.pipeline import Pipeline

# --- Dataset Generation ---
X, y = make_classification(n_samples=1000, n_features=10, random_state=42)

# ==========================================
# Task 1 — Reproduce and Identify Leakage
# ==========================================
# Flawed approach: Scaling before splitting
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train_leak, X_test_leak, y_train_leak, y_test_leak = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

model_leakage = LogisticRegression()
model_leakage.fit(X_train_leak, y_train_leak)

print("--- Task 1: Flawed Approach ---")
print(f"Train Accuracy: {model_leakage.score(X_train_leak, y_train_leak):.4f}")
print(f"Test Accuracy: {model_leakage.score(X_test_leak, y_test_leak):.4f}")
print("Leakage Identification: Scaling the entire dataset before splitting introduces 'Data Leakage' because the scaler 'sees' the distribution (mean/std) of the test set during the fit process. This leads to biased and overly optimistic performance estimates.\n")


# ==========================================
# Task 2 — Fix the Workflow Using a Pipeline
# ==========================================
# Correct approach: Split first, then use Pipeline
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('clf', LogisticRegression())
])

# Use cross-validation on the training set
cv_scores = cross_val_score(pipeline, X_train, y_train, cv=5)

print("--- Task 2: Pipeline & CV ---")
print(f"Mean CV Accuracy: {cv_scores.mean():.4f}")
print(f"Standard Deviation: {cv_scores.std():.4f}\n")


# ==========================================
# Task 3 — Experiment with Decision Tree Depth
# ==========================================
depths = [1, 5, 20]
tree_results = []

for d in depths:
    # We use the split from Task 2
    dt = DecisionTreeClassifier(max_depth=d, random_state=42)
    dt.fit(X_train, y_train)

    train_acc = dt.score(X_train, y_train)
    test_acc = dt.score(X_test, y_test)

    tree_results.append({
        "Max Depth": d,
        "Train Accuracy": train_acc,
        "Test Accuracy": test_acc
    })

# Display Results
df_tree = pd.DataFrame(tree_results)
print("--- Task 3: Decision Tree Results ---")
print(df_tree)

print("\nExplanation:")
print("- Max Depth 1: Underfits. The model is too simple to capture patterns.")
print("- Max Depth 20: Overfits. High train accuracy (near 1.0) but test accuracy drops as it memorizes noise.")
print("- Max Depth 5: Best Balance. It provides the best generalization on the test set.")